/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_HELLOWORLDJC_H
#define IDL2JNI_GENERATED_HELLOWORLDJC_H
#include "HelloWorldC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "HelloWorld_Export.h"
/* Generated by D:\Document\EDUKASI\MAGANG\LEN\OpenDDS-Java\OpenDDS-3.28.1\bin\idl2jni running on input file HelloWorld.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: HelloWorld */



/* Begin STRUCT: Message */

HelloWorld_Export
void copyToCxx (JNIEnv *jni, HelloWorld::Message &target, jobject source);
HelloWorld_Export
void copyToJava (JNIEnv *jni, jobject &target, const HelloWorld::Message &source, bool createNewObject = false);

/* End STRUCT: Message */

/* End MODULE: HelloWorld */
#endif /* IDL2JNI_GENERATED_HELLOWORLDJC_H */
