#include "HelloWorldJC.h"
#include "idl2jni_runtime.h"

/* Generated by D:\Document\EDUKASI\MAGANG\LEN\OpenDDS-Java\OpenDDS-3.28.1\bin\idl2jni running on input file HelloWorld.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */


/* Begin MODULE: HelloWorld */



/* Begin STRUCT: Message */

void copyToCxx (JNIEnv *jni, HelloWorld::Message &target, jobject source)
{
  jclass clazz = jni->GetObjectClass (source);
  {
    jfieldID fid = jni->GetFieldID (clazz, "id", "I");
    target.id = jni->GetIntField (source, fid);
  }
  {
    jfieldID fid = jni->GetFieldID (clazz, "text", "Ljava/lang/String;");
    jobject obj = jni->GetObjectField (source, fid);
    copyToCxx (jni, target.text, obj);
    jni->DeleteLocalRef (obj);
  }
  jni->DeleteLocalRef (clazz);
}

void copyToJava (JNIEnv *jni, jobject &target, const HelloWorld::Message &source, bool createNewObject)
{
  jclass clazz;
  if (createNewObject)
    {
      clazz = findClass (jni, "HelloWorld/Message");
      jmethodID ctor = jni->GetMethodID (clazz, "<init>", "()V");
      target = jni->NewObject (clazz, ctor);
    }
  else
    {
      clazz = jni->GetObjectClass (target);
    }
  {
    jfieldID fid = jni->GetFieldID (clazz, "id", "I");
    jni->SetIntField (target, fid, source.id);
  }
  {
    jfieldID fid = jni->GetFieldID (clazz, "text", "Ljava/lang/String;");
    jobject obj = createNewObject ? 0 : jni->GetObjectField (target, fid);
    copyToJava (jni, obj, source.text, createNewObject);
    jni->SetObjectField (target, fid, obj);
    jni->DeleteLocalRef (obj);
  }
  jni->DeleteLocalRef (clazz);
}


/* End STRUCT: Message */

/* End MODULE: HelloWorld */
