// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.20
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// D:\Document\EDUKASI\MAGANG\LEN\OpenDDS-Java\OpenDDS-3.28.1\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:631

#ifndef _TAO_IDL_HELLOWORLDTYPESUPPORTS_4KUFYP_CPP_
#define _TAO_IDL_HELLOWORLDTYPESUPPORTS_4KUFYP_CPP_


#include "HelloWorldTypeSupportS.h"

#endif /* ifndef */

