#include "HelloWorldTypeSupportJC.h"
#include "idl2jni_runtime.h"

/* Generated by D:\Document\EDUKASI\MAGANG\LEN\OpenDDS-Java\OpenDDS-3.28.1\bin\idl2jni running on input file HelloWorldTypeSupport.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */
