/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_HELLOWORLDTYPESUPPORTJC_H
#define IDL2JNI_GENERATED_HELLOWORLDTYPESUPPORTJC_H
#include "HelloWorldTypeSupportC.h"
#include "HelloWorldJC.h"
#include "HelloWorld_Export.h"
/* Generated by D:\Document\EDUKASI\MAGANG\LEN\OpenDDS-Java\OpenDDS-3.28.1\bin\idl2jni running on input file HelloWorldTypeSupport.idl */


/* Begin MODULE: OpenDDS */


/* End MODULE: OpenDDS */
#endif /* IDL2JNI_GENERATED_HELLOWORLDTYPESUPPORTJC_H */
